parameters:
    ezsystems.tweetbundle.fieldType.eztweet.class: EzSystems\TweetFieldTypeBundle\eZ\Publish\FieldType\Tweet\Type
    ezsystems.tweetbundle.fieldType.eztweet.converter.class: EzSystems\TweetFieldTypeBundle\eZ\Publish\FieldType\Tweet\LegacyConverter

services:
    ezsystems.tweetbundle.fieldType.eztweet:
        parent: ezpublish.fieldType
        class: %ezsystems.tweetbundle.fieldType.eztweet.class%
        tags:
            - {name: ezpublish.fieldType, alias: eztweet}

    ezsystems.tweetbundle.fieldType.eztweet.converter:
        class: %ezsystems.tweetbundle.fieldType.eztweet.converter.class%
        tags:
            - {name: ezpublish.storageEngine.legacy.converter, alias: eztweet}
